version: '3.1'

services: 
  nestjs_api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db_mysql
    environment:
      - PORT=3000
      - NODE_ENV=production
    # volumes:
    #   - ./src:/usr/src/app/src
    networks:
      - nesjs-network
  db_mysql:
    image: mysql
    restart: always
    ports:
      - 3307:3307
    environment:
      - MYSQL_USER=potae
      - MYSQL_PASSWORD=Pass@word1
      - MYSQL_ROOT_PASSWORD=Pass@word1
      - MYSQL_DATABASE=borrow
      - MYSQL_TCP_PORT=3307
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - nesjs-network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db_mysql
    ports:
      - 8080:80
    environment:
      - PMA_PORT=3307
      - PMA_HOST=db_mysql
      - PMA_ARBITRARY=1
    networks:
      - nesjs-network

volumes:
  dbdata:

networks:
  nesjs-network:
    driver: bridge